// <auto-generated />
using System;
using AMSProj.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMSProj.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250701171131_AddClassrooms")]
    partial class AddClassrooms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMSProj.Models.Building", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Building_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CampusID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nearest_Building")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoOfFloors")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CampusID");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("AMSProj.Models.Campus", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoOfBuildings")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Campuses");
                });

            modelBuilder.Entity("AMSProj.Models.Classroom", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Classroom_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DepartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FloorID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("FloorID");

                    b.ToTable("CLassrooms");
                });

            modelBuilder.Entity("AMSProj.Models.Department", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Department_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FloorID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("FloorID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("AMSProj.Models.Floor", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuildingID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FloorNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BuildingID");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("AMSProj.Models.Lab", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FloorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Lab_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("FloorID");

                    b.ToTable("Labs");
                });

            modelBuilder.Entity("AMSProj.Models.Building", b =>
                {
                    b.HasOne("AMSProj.Models.Campus", "Campus")
                        .WithMany("Buildings")
                        .HasForeignKey("CampusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("AMSProj.Models.Classroom", b =>
                {
                    b.HasOne("AMSProj.Models.Department", "Department")
                        .WithMany("Classrooms")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMSProj.Models.Floor", "Floor")
                        .WithMany("Classrooms")
                        .HasForeignKey("FloorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("AMSProj.Models.Department", b =>
                {
                    b.HasOne("AMSProj.Models.Floor", "Floor")
                        .WithMany("Departments")
                        .HasForeignKey("FloorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("AMSProj.Models.Floor", b =>
                {
                    b.HasOne("AMSProj.Models.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("AMSProj.Models.Lab", b =>
                {
                    b.HasOne("AMSProj.Models.Department", "Department")
                        .WithMany("Labs")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMSProj.Models.Floor", "Floor")
                        .WithMany("Labs")
                        .HasForeignKey("FloorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("AMSProj.Models.Building", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("AMSProj.Models.Campus", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("AMSProj.Models.Department", b =>
                {
                    b.Navigation("Classrooms");

                    b.Navigation("Labs");
                });

            modelBuilder.Entity("AMSProj.Models.Floor", b =>
                {
                    b.Navigation("Classrooms");

                    b.Navigation("Departments");

                    b.Navigation("Labs");
                });
#pragma warning restore 612, 618
        }
    }
}
